# Generated by Django 5.0.4 on 2024-05-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_attendancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='student',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
