# Generated by Django 5.0.4 on 2024-05-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_attendancerecord_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
